spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.37.90.193:3306/ljk
    username: root
    password: Ljk123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
pagehelper:
  helper-dialect: mysql
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.springBootlayui.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.example.springbootlayui.dao: debug
